spring:
    application:
        name: filmapi
    datasource:
        url: jdbc:mysql://localhost:3306/apifilm?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: none
