name: "Mi primera pipeline"

on:
    workflow_dispatch

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: "Hello world step"
              run: echo "Hello world!"